version: "3.2"    
services:
    reddit-md-save:
        build: .
        image: reddit-md-save:latest
        environment:
          REDDIT_USERNAME:
          REDDIT_PASSWORD:
          REDDIT_CLIENT_ID:
          REDDIT_SECRET:
        volumes:
          - "./archive:/opt/app/archive"
        command: ["saved", "--download-videos", "--use-id"]
